//Dom - stands for document object model. it represents the webpage as a form of object or a treee structure that contains all the elements of the webpage . it allows to manipulate the webpage using js by accessing the elements and chnging their properties or adding new elements to webpage.


// methods to access the elements in the webpage
// getElementsByID, getElementsByClassName(), getElementsByClassTagName(), querySelector(), querySelectorAll()
//mostly used getElementsByID, querySelector()

// console.log(document.getElementsByTagName("h1"))
// console.log(document.getElementsByClassName("text"))
// console.log(document.getElementByID("heading"))


//query sel returns only first element
//console.log(document.querySelector("#heading"))
//console.log(document.querySelector(".text"))
//console.log(document.querySelectorAll(".text"))
//all will return all class elements

//console.log(document.querySelector("h1"))



//accessing the content of the element
//innerText , innerHTML , textContent

//innerText- it returns the visible text content of the element.it does not include the hidden text or the text that is generated by css.
//innerHTML- it returns the html content of the element. it includes the text as well as the html tags.
//textContent- it returns the text content of the element. it includes the hidden text as well as the etxt that is generated by css. it does not include the html tags.

//Ye simple content dekhne k liye
// let heading = document.getElementById("heading").textContent
// console.log(heading)


// let heading = document.getElementById("heading").innerText
// console.log(heading)


// TO CHNGE THE DOCUMENT CONTENT

// let heading = document.getElementById("heading")
// heading.textContent = "this is a heading created by js"

// phle humne element to get kra getElementById se nd usko var mai store kra diya then textContent  use krke content chnge kra


//event - action happening on the webpage. it can be triggered by user iteration or by the brower itself.

// eventListener - function that is called when the event is triggered. it can be used to perform some action when the event is triggered.
// click , mouseover, mousedown 

// let heading = document.getElementById("heading")
// // phle element ko get krna
// heading.addEventListener("click",function(){
//     heading.textContent = "This heading is chnaged by dom manupulation"
// })
//addEventListener require 2arguments - event konsa hoga nd us event k response mai konsa function chlna chhaiye


// let button = document.getElementById("btn")

// button.addEventListener("click",function(){
//     button.textContent = "This heading is chnaged by dom manupulation"
// })


// let msg = document.getElementById("wlcm-msg")
// let login = document.getElementById("login-btn")

// login.addEventListener("click",function(){
//     let username = prompt("Enter your name")
//     msg.textContent = `Hello ${username}`
// })



let button = document.querySelector(".mode-btn")
let para = document.querySelector(".text")
let card = document.querySelector(".container")


button.addEventListener("click", function () {
    // document.body.style.color= "white"
    // document.body.style.backgroundColor= "black"
    // // agr humko body mai chnge krna usko normally document k sth lahga kr kr skte ismai body ki alg obj create ho jati nd style kibhi
    // // css property ismai access krne k liye camel case ka use krte hai
    // para.style.color = "red"
    // button.textContent= "Ligth Mode"
    // // agr body k ander kisi element ko krna to ese krte 


    if (button.textContent === "Dark Mode") {
        document.body.style.color = "white"
        document.body.style.backgroundColor = "black"
        button.textContent = "Light Mode"
        card.style.backgroundColor ="white"
    }
    else{
        document.body.style.color = "black"
        document.body.style.backgroundColor = "white"
        button.textContent = "Dark Mode"
    }
})
//this is how we chnge element css


